apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-02
  name: deployment-02
  namespace: dev-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-02
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-02
    spec:
      containers:
      - image: nginx
        name: pod-in-deployment-02-container
        resources: {}
status: {}
