apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deployment-02
  name: service-02
  namespace: dev-namespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deployment-02
status:
  loadBalancer: {}
