apiVersion: v1
kind: Pod
metadata:
  name: require-during-scheduling-pod
  namespace: scheduler-ns
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: drink
            operator: In
            #operator: NotIn
            values:
            - pepsi