apiVersion: v1
kind: Pod
metadata:
  name: toleration-equals-pod
  namespace: scheduler-ns
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "color"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"

  nodeSelector:
    drink: cocacola
    # drink: pepsi