apiVersion: v1
kind: Pod
metadata:
  name: toleration-exists-pod
  namespace: scheduler-ns
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "color"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    drink: cocacola
    # drink: pepsi