# Create new taint
# kubectl taint nodes k8s-worker-1 animal=dog:PreferNoSchedule
# kubectl taint nodes k8s-worker-2 animal=cat:NoSchedule

apiVersion: v1
kind: Pod
metadata:
  name: toleration-prefer-no-schedule-pod
  namespace: scheduler-ns
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "animal"
    operator: "Equal"
    value: "chicken"
    effect: "PreferNoSchedule"
