apiVersion: v1
kind: Pod
metadata:
  labels:
    color: blue
  name: liveness-pod
  namespace: dev-namespace
spec:
  containers:
  - image: busybox
    name: liveness-container
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 15; rm -rf /tmp/healthy; sleep 100
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5