apiVersion: v1
kind: Pod
metadata:
  labels:
    color: blue
  name: liveness-pod
  namespace: dev-namespace
spec:
  containers:
  - image: nginx
    name: readiness-container
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5