apiVersion: v1
kind: Pod
metadata:
  labels:
    color: blue
  name: multi-container-pod
  namespace: prod-namespace
spec:
  containers:
  - image: nginx
    name: container-1
  - image: busybox
    name: container-2
    args:
      - /bin/sh
      - -c
      - sleep 100