apiVersion: v1
kind: Pod
metadata:
  labels:
    color: blue
  name: init-pod
  namespace: prod-namespace
spec:
  containers:
  - image: nginx
    name: container-1
  initContainers:
  - image: busybox
    name: init-container
    command: ['sh', '-c', "sleep 30"]
